xolon/blueprints/wallet/__init__.py
from flask import Blueprint

wallet_bp = Blueprint("wallet", __name__)

from . import routes

xolon/blueprints/wallet/routes.py
import string
from time import sleep
from io import BytesIO
from base64 import b64encode
from qrcode import make as qrcode_make
from decimal import Decimal
from flask import render_template, jsonify, request, redirect, url_for, flash
from flask_login import login_required, current_user
from datetime import datetime
from xolon.blueprints.wallet import wallet_bp
from xolon.decorators import check_confirmed
from xolon.library.docker import docker
from xolon.library.helpers import capture_event
from xolon.library.jsonrpc import Wallet, to_atomic
from xolon.library.cache import cache
from xolon.forms import Send, Delete, Restore, Secrets
from xolon.token import generate_token, validate_token
from xolon.factory import db, bcrypt
from xolon.models import User


@wallet_bp.route('/wallet/setup', methods=['GET', 'POST'])
@login_required
@check_confirmed
def setup():
    if current_user.wallet_created:
        return redirect(url_for('wallet.dashboard'))
    else:
        restore_form = Restore()
        if restore_form.validate_on_submit():
            c = docker.create_wallet(current_user.id, restore_form.seed.data)
            cache.store_data(f'init_wallet_{current_user.id}', 30, c)
            capture_event(current_user.id, 'restore_wallet')
            current_user.wallet_created = True
            db.session.commit()
            return redirect(url_for('wallet.loading'))
        else:
            return render_template(
                'wallet/setup.html',
                restore_form=restore_form
            )


@wallet_bp.route('/wallet/loading')
@login_required
@check_confirmed
def loading():
    if current_user.wallet_connected and current_user.wallet_created:
        return redirect(url_for('wallet.dashboard'))

    if current_user.wallet_created is False:
        return redirect(url_for('wallet.setup'))

    return render_template('wallet/loading.html')


@wallet_bp.route('/wallet/dashboard')
@login_required
@check_confirmed
def dashboard():
    send_form = Send()
    delete_form = Delete()
    _address_qr = BytesIO()
    all_transfers = list()
    wallet = Wallet(
        proto='http',
        host='127.0.0.1',
        port=current_user.wallet_port,
        username=current_user.id,
        password=current_user.wallet_password
    )
    if not docker.container_exists(current_user.wallet_container):
        current_user.clear_wallet_data()
        return redirect(url_for('wallet.loading'))

    if not wallet.connected:
        sleep(1.5)
        return redirect(url_for('wallet.loading'))

    address = wallet.get_address()

    transfers = wallet.get_transfers()
    for _type in transfers:
        for tx in transfers[_type]:
            all_transfers.append(tx)

    balances = wallet.get_balances()

    qr_uri = f'xolentum:{address}?tx_description={current_user.email}'
    qrcode_make(qr_uri).save(_address_qr)
    qrcode = b64encode(_address_qr.getvalue()).decode()

    capture_event(current_user.id, 'load_dashboard')

    _show_secrets = request.args.get('show_secrets', 'default')
    _token = request.args.get('token', 'default')

    if request.args.get('show_secrets', 'no') == 'true' and _token and \
            validate_token(_token, 60) == current_user.email:
        seed = wallet.seed()
        spend_key = wallet.spend_key()
        view_key = wallet.view_key()

        return render_template(
            'wallet/dashboard.html',
            transfers=all_transfers,
            sorted_txes=_get_sorted_txs(transfers),
            balances=balances,
            address=address,
            qrcode=qrcode,
            send_form=send_form,
            delete_form=delete_form,
            user=current_user,
            seed=seed,
            spend_key=spend_key,
            view_key=view_key,
        )

    else:
        secrets_form = Secrets()

        return render_template(
            'wallet/dashboard.html',
            transfers=all_transfers,
            sorted_txes=_get_sorted_txs(transfers),
            balances=balances,
            address=address,
            qrcode=qrcode,
            send_form=send_form,
            secrets_form=secrets_form,
            delete_form=delete_form,
            user=current_user,
        )


@wallet_bp.route('/wallet/connect')
@login_required
@check_confirmed
def connect():
    if current_user.wallet_created is False:
        data = {
            'result': 'fail',
            'message': 'Wallet not yet created'
        }
        return jsonify(data)

    if current_user.wallet_connected is False:
        wallet = docker.start_wallet(current_user.id)
        port = docker.get_port(wallet)
        current_user.wallet_connected = docker.container_exists(wallet)
        current_user.wallet_port = port
        current_user.wallet_container = wallet
        current_user.wallet_start = datetime.utcnow()
        db.session.commit()
        capture_event(current_user.id, 'start_wallet')
        data = {
            'result': 'success',
            'message': 'Wallet has been connected'
        }
    else:
        data = {
            'result': 'fail',
            'message': 'Wallet is already connected'
        }

    return jsonify(data)


@wallet_bp.route('/wallet/create')
@login_required
@check_confirmed
def create():
    if current_user.wallet_created is False:
        c = docker.create_wallet(current_user.id)
        cache.store_data(f'init_wallet_{current_user.id}', 30, c)
        capture_event(current_user.id, 'create_wallet')
        current_user.wallet_created = True
        db.session.commit()
        return redirect(url_for('wallet.loading'))
    else:
        return redirect(url_for('wallet.dashboard'))


@wallet_bp.route('/wallet/status')
@login_required
@check_confirmed
def status():
    user_vol = docker.get_user_volume(current_user.id)
    create_container = cache.get_data(f'init_wallet_{current_user.id}')
    data = {
        'created': current_user.wallet_created,
        'connected': current_user.wallet_connected,
        'port': current_user.wallet_port,
        'container': current_user.wallet_container,
        'volume': docker.volume_exists(user_vol),
        'initializing': docker.container_exists(create_container)
    }
    return jsonify(data)


@wallet_bp.route('/wallet/secrets', methods=['GET', 'POST'])
@login_required
@check_confirmed
def secrets():
    secrets_form = Secrets()

    if secrets_form.validate_on_submit():
        password_matches = bcrypt.check_password_hash(
            current_user.password,
            secrets_form.password.data
        )

        if not password_matches:
            flash('Invalid password.')
            return redirect(url_for('wallet.dashboard') + '#secrets')

        else:
            _token = generate_token(current_user.email)
            return redirect(url_for('wallet.dashboard') + f'?show_secrets=true&token={_token}'
                            + '#secrets')


@wallet_bp.route('/wallet/send', methods=['GET', 'POST'])
@login_required
@check_confirmed
def send():
    send_form = Send()
    redirect_url = url_for('wallet.dashboard') + '#send'
    wallet = Wallet(
        proto='http',
        host='127.0.0.1',
        port=current_user.wallet_port,
        username=current_user.id,
        password=current_user.wallet_password
    )
    if send_form.validate_on_submit():
        address = str(send_form.address.data)
        payment_id = str(send_form.payment_id.data) or None
        # noinspection PyUnresolvedReferences
        user = User.query.get(current_user.id)

        # Check if Xolentum wallet is available
        if wallet.connected is False:
            flash('Wallet RPC interface is unavailable at this time. Try again later.')
            capture_event(user.id, 'tx_fail_address_invalid')
            return redirect(redirect_url)

        # Validate destination address
        if not wallet.validate_address(address):
            flash('Invalid Xolentum address provided.')
            capture_event(user.id, 'tx_fail_address_invalid')
            return redirect(redirect_url)

        # Check if we're sweeping or not
        if send_form.amount.data == 'all':
            tx = wallet.transfer(address, None, 'sweep_all')

        else:
            # Make sure the amount provided is a number
            # noinspection PyBroadException
            try:
                amount = to_atomic(Decimal(send_form.amount.data))

            except:
                flash('Invalid Xolentum amount specified.')
                capture_event(user.id, 'tx_fail_amount_invalid')
                return redirect(redirect_url)

            # Validate Payment ID
            if payment_id and not len(payment_id) in [16, 32] and not all(c in string.hexdigits for c in payment_id):
                flash('Invalid payment ID specified.')
                return redirect(redirect_url)

            # Send transfer
            tx = wallet.transfer(address, amount, payment_id=payment_id)

        # Inform user of result and redirect
        if 'message' in tx:
            msg = tx['message'].capitalize()
            msg_lower = tx['message'].replace(' ', '_').lower()
            flash(f'There was a problem sending the transaction: {msg}')
            capture_event(user.id, f'tx_fail_{msg_lower}')
        else:
            flash('Successfully sent transfer.')
            capture_event(user.id, 'tx_success')

        return redirect(redirect_url)
    else:
        for field, errors in send_form.errors.items():
            flash(f'{send_form[field].label}: {", ".join(errors)}')
        return redirect(redirect_url)


def _get_sorted_txs(_txs):
    total = 0
    txs = {}
    sorted_txs = {}
    for tx_type in _txs:
        for t in _txs[tx_type]:
            txs[t['txid']] = {
                'type': tx_type,
                'amount': t['amount'],
                'timestamp': t['timestamp'],
                'fee': t['fee']
            }

    for i in sorted(txs.items(), key=lambda x: x[1]['timestamp']):

xolon/templates/wallet/dashboard.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    {% include 'navbar.html' %}

    <section class="section2">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Wallet Information</h2>
          <h4>Address:</h4>
          <p class="slim small">{{ address }}</p>
          <br>
          <img src="data:image/png;base64,{{ qrcode }}" width=200 class="center" alt="wallet_qr">
          <hr><br>
          <h4>Balance</h4>
          <p class="inline">{{ balances[1] | from_atomic }} XOL ({{ (balances[0] - balances[1]) | from_atomic }} locked)</p>
          <span class="dashboard-buttons">
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#transfers">View TX History</a>
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#send">Send TX</a>
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#secrets">View Secrets</a>
          </span>
        </div>
      </div>
    </section>

    <section class="section1" id="transfers">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Transaction History</h2>
          <div style="width: 70%; text-align: center; margin: 0 auto;">
            <canvas id="xol_wallet"></canvas>
            <canvas id="xol_wallet_scatter"></canvas>
          </div>

          <script src="/static/js/Chart.bundle.min.js"></script>
          <link rel="stylesheet" href="/static/css/Chart.min.css"/>
          <script>
              const xolentum = '#2B2D42';
              const set_title = function (t) {
              return {
                  display: true,
                  text: t,
                  fontColor: 'white',
              }
          };

          let ctx = document.getElementById('xol_wallet').getContext('2d');
          new Chart(ctx, {
            type: 'line',
            data: {
              labels: [0, {% for i in sorted_txes %}'{{ sorted_txes[i].timestamp | datestamp  }}',{% endfor %}],
              datasets: [{
                label: 'Balance',
                backgroundColor: xolentum,
                borderColor: xolentum,
                data: [0, {% for i in sorted_txes %}{{ sorted_txes[i].total | from_atomic }},{% endfor %}],
                fill: false,
              }]
            },
            options: {
              title: set_title('Xolentum Wallet Balance')
            }
          });
          </script>
          <table class="table table-striped table-hover table-responsive table-responsive-sm tx-table">
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Tx ID</th>
              <th>Amount</th>
              <th>Confirmations</th>
              <th>Height</th>
              <th>Fee</th>
            </tr>
            {% if transfers %}
            {% for tx in transfers | sort(attribute='timestamp', reverse=True) %}
              {% if tx.type == 'pool' %}<tr class="table-warning">{% else %}<tr>{% endif %}
                <td>{{ tx.timestamp | datestamp }}</td>
                <td>{{ tx.type }}</td>
                <td><a href="https://explorer.xolentum.org/?hash={{ tx.txid }}#blockchain_transaction" target="_blank">{{ tx.txid | truncate(12) }}</a></td>
                <td>{{ tx.amount | from_atomic }} XOL</td>
                <td>{{ tx.confirmations }}</td>
                <td>{{ tx.height }}</td>
                <td>{{ tx.fee | from_atomic }} XOL</td>
              </tr>
            {% endfor %}
            {% endif %}
          </table>
        </div>
      </div>
    </section>

    <section class="section2" id="send">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Send Transaction</h2>
          <i class="fa fa-qrcode fa-2x" id="startVideo"></i><br /><br />
          <div class="hidden" id="preview">
            <p>Show me a QR code!</p>
            <video id="video" width="300" height="200"></video>
            <br /><button id="stopVideo">Cancel</button>
          </div>
          <form method="POST" action="{{ url_for('wallet.send') }}" class="send-form">
              {{ send_form.csrf_token }}
              <div class="form-group">
                {{ send_form.address.label }}
                {{ send_form.address }}
              </div>
              <div class="form-group">
                {{ send_form.amount.label }}
                {{ send_form.amount }}
              </div>
              <div class="form-group">
                {{ send_form.payment_id.label }}
                {{ send_form.payment_id }}
              </div>
              <ul>
                {% for field, errors in send_form.errors.items() %}
                    <li>{{ send_form[field].label }}: {{ ', '.join(errors) }}</li>
                {% endfor %}
              </ul>
              <input type="submit" value="Send" class="btn btn-link btn-outline btn-xl">
              <a class="btn btn-link btn-outline btn-xl" style="margin-left: 10px" onclick="genPaymentID()">Generate</a>
              <script>
                  function genPaymentID() {
                      const genRanHex = size => [...Array(size)].map(() => Math.floor(Math.random() * 16).toString(16)).join('');
                      document.getElementById('payment_id').value = genRanHex(16);
                  }
              </script>
          </form>
        </div>
      </div>
    </section>

    <section class="section1" id="secrets">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Secrets</h2>
          <p>You need to save the secrets below; write them down on a physical medium and keep it in a safe location.</p>
          <hr><br>
            {% if secrets_form is defined %}
              <form method="POST" action="{{ url_for('wallet.secrets') }}" class="secrets-form">
                  {{ secrets_form.csrf_token }}
                  <div class="form-group">
                    {{ secrets_form.password.label }}
                    {{ secrets_form.password }}
                  </div>
                  <ul>
                    {% for field, errors in secrets_form.errors.items() %}
                        <li>{{ secrets_form[field].label }}: {{ ', '.join(errors) }}</li>
                    {% endfor %}
                  </ul>
                  <input type="submit" value="Verify" class="btn btn-link btn-outline-inverse btn-xl">
              </form>
            {% else %}
              <h3>Mnemonic Seed</h3>
              <p class="small">{{ seed }}</p>
              <br>
              <h3>Spend Key</h3>
              <p class="small">{{ spend_key }}</p>
              <br>
              <h3>View Key</h3>
              <p class="small">{{ view_key }}</p>
            {% endif %}
        </div>
      </div>
    </section>

    <section class="section2" id="send">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Reset Account</h2>
          <p>Please ensure you have copied the mnemonic seed from the secrets above if there are still funds associated with the keys.</p>
          <p>It is highly recommended to make a new wallet on your own and transferring funds there to ensure only you have full ownership and visibility into the private keys / seed. Not your keys, not your crypto!</p>
            <form method="POST" action="{{ url_for('auth.delete') }}" class="send-form">
              {{ delete_form.csrf_token }}
              {% for f in delete_form %}
                {% if f.name != 'csrf_token' %}
                  <div class="form-group">
                    {{ f.label }}
                    {{ f }}
                  </div>
                {% endif %}
              {% endfor %}
              <ul>
              {% for field, errors in delete_form.errors.items() %}
                  <li>{{ send_form[field].label }}: {{ ', '.join(errors) }}</li>
              {% endfor %}
              </ul>
              <input type="submit" value="Delete" class="btn btn-link btn-outline btn-xl">
          </form>
        </div>
      </div>
    </section>

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

  </body>

</html>

xolon/templates/wallet/loading.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    {% include 'navbar.html' %}

    <section class="section2">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Wallet is being connected.</h2>
            <p>Your wallet is connecting. This page should auto-refresh when it's ready ... if not, click the button below. <br /><br />If you are restoring from a seed, please allow upto a couple hours for the process to complete.</p>
          <span class="dashboard-buttons">
              <a class="btn btn-lg btn-link btn-outline btn-xl" href="{{ url_for('wallet.dashboard') }}">Check Again</a>
          </span>
        </div>
      </div>
    </section>

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

  </body>

</html>

xolon/templates/wallet/setup.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    {% include 'navbar.html' %}

    <section class="section2">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Setup Wallet</h2>
          <p>Choose an option below in order to continue creating your wallet:</p>

          <hr><br /><br />

          <a class="btn btn-lg btn-link btn-outline btn-xl" href="{{ url_for('wallet.create') }}">Create new wallet</a>

          <hr><br /><br />

          <form method="POST" action="{{ url_for('wallet.setup') }}" class="send-form">
              <p><strong>NOTE: </strong><br>Your mnemonic seed is sent to the server for restoring the wallet.</p>
              {{ restore_form.csrf_token }}
              {% for f in restore_form %}
                {% if f.name != 'csrf_token' %}
                  <div class="form-group">
                    {{ f.label }}
                    {{ f }}
                  </div>
                {% endif %}
              {% endfor %}
              <ul>
              {% for field, errors in restore_form.errors.items() %}
                  <li>{{ restore_form[field].label }}: {{ ', '.join(errors) }}</li>
              {% endfor %}
              </ul>
              <input type="submit" value="Restore From Seed" class="btn btn-link btn-outline btn-xl">
          </form>
        </div>
      </div>
    </section>

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

  </body>

</html>